# Reference: http://docs.oracle.com/cd/E23104_01/sysreqs1221/sysrs.htm#sthref18

packages_list:
  - 'binutils'
  - 'compat-libcap1'
  - 'compat-libstdc++-33.x86_64'
  - 'gcc.x86_64'
  - 'gcc-c++.x86_64'
  - 'glibc.x86_64'
  - 'glibc.i686'
  - 'glibc-devel.x86_64'
  - 'libaio.x86_64'
  - 'libaio-devel.x86_64'
  - 'libgcc.x86_64'
  - 'libgcc.i686'
  - 'libstdc++.x86_64'
  - 'libstdc++.i686'
  - 'libstdc++-devel.x86_64'
  - 'ksh'
  - 'make'
  - 'sysstat'
kernel_params:
        kernel.shmmax: 4294967295
soft_no_file: 4096
hard_no_file: 65536
soft_nproc: 2047
hard_nproc: 16384

# JDK installer and target folder
jdk_installation_archive: 'jdk-8u121-linux-x64.tar.gz'
jdk_version: '1.8'
jdk_folder: '{{ jdk_home }}/jdk1.8.0_121'
jdk_installer_url: '{{ httpfs_url }}/jdk/{{ jdk_version }}/{{ jdk_installation_archive }}'